@url = http://localhost:3000/api/payroll

###
GET {{url}}?page=2&size=10
Content-Type: application/json

###
GET {{url}}/show/Juan?page=1&size=10
Content-Type: application/json

###
GET {{url}}/edit/5931
Content-Type: application/json

###
POST {{url}}/store
Content-Type: application/json

{
  "typePayroll": 10,
  "regionId": 2,
  "municipalityId": 2,
  "documentNumber": 18444814,
  "fullName": "JOISE GARCIA",
  "birthday": "1986-07-25",
  "age": 35
}

###
DELETE {{url}}/destroy/18444814
Content-Type: application/json